FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir paho-mqtt==1.6.1

COPY Data_Dummy_Nodered__1_.py ./simulator.py

# Default values — semua bisa di-override dari docker-compose environment:
ENV MQTT_BROKER=emqx
ENV MQTT_PORT=1883
ENV MQTT_USERNAME=edge_service
ENV MQTT_PASSWORD=edge_secret_2026
ENV SITE_ID=POLMAN_BANDUNG_EDGE
ENV MACHINE_ID=dmg_mori_ntx1000
ENV PUBLISH_INTERVAL=2

CMD ["python", "simulator.py"]
